#server.address=92.52.151.6
#server.address=192.168.1.6
spring:
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false  # Fix Postgres JPA Error: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/edbot_tests
    username: dbuser
    password: dbpassword
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 60000
  cache:
    ehcache:
      config: ehcache.xml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration


server:
  port: 8081

bot:
  profile:
    name: Rshu Bot
    avatar: